### ISSUE TITLE
const transform = require('../libs/transform');

### ISSUE THREAD

**Issue by blackmiaool** [camiler/react-touch-scroll-view#1]
然而这库里面并没有这个文件

**Comment by camiler** [comment]
@blackmiaool 这个嘛，就是直接把这个[transform.js](https://github.com/AlloyTeam/AlloyTouch/blob/master/transformjs/transform.js)放到工程的libs下面。也是做项目的时候需要这个效果嘛，完后觉得有必要存下来，就直接放上来了，也没有demo什么的。

**Comment by blackmiaool** [comment]
那建议你使用gist

**Comment by camiler** [comment]
@blackmiaool 嗯，我看看，谢谢！
